# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Solutions
    url: /solutions
    weight: 10
  - name: Partners
    url: /partners
    weight: 20
  - name: Locations
    url: /locations
    weight: 30
  - name: Pricing
    url: /pricing
  - name: Resources
    weight: 40
    hasChildren: true
  - parent: Resources
    name: Blog
    url: blog/
