# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Remove HugoBlox blurb
i_am_a_sponsor: true

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Deploy a flexible private network in minutes.'
    twitter: 'megaportnetwork'
  analytics:
    google_analytics: ''    
    plausible: ''    
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "Book a Demo"
      url: /demo
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: '© {year} Megaport'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
